### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by insxa** [ha1fdan/HetznerCloudExtension#2]
How to setup  Configurable options from admin panel ?
Like example, or screenshot ?

**Comment by ha1fdan** [comment]
Hi @insxa, I can show you both a example and a screenshot; the following images are from my [development discord server](https://discord.gg/n8hpbek59q). Join it for more questions, and please do not open 3 issues for questions, please ask questions in the [Discord](https://discord.gg/n8hpbek59q).

![image](https://github.com/user-attachments/assets/4f3e17ce-d79b-40dc-a2fb-6fe881763e58)
![image](https://github.com/user-attachments/assets/3fe6c46b-913a-41e9-9f16-9f3db4b93d3c)
![image](https://github.com/user-attachments/assets/74a3bd56-46eb-407c-a5f2-b2a78beb1f47)
sorry if some of the text is in Danish :)
and the list is the same you see under settings
![image](https://github.com/user-attachments/assets/034ce04f-f66c-4982-b33a-54ec0fddcafe)

**Comment by insxa** [comment]
Can you resend your discord server ? i cant jon

**Comment by ha1fdan** [comment]
> Can you resend your discord server ? i cant jon

https://discord.gg/RhBKRKR57R
